export const theme = {
  colors: {
    white: "#FFF",
    black: "#000",
    gray: "#8F8F8F",
    red: "#FF0000",
    darkRed: "#CC0000",
    blue: "#3B4CCA",
    yellow: "#FFDE00",
    darkYellow: "#B3A125",
  },
  spacings: {
    xxxsmall: "0.4rem",
    xxsmall: "0.8rem",
    xsmall: "1.6rem",
    small: "2.4rem",
    medium: "3.2rem",
    large: "4.0rem",
    xlarge: "4.8rem",
    xxlarge: "5.6rem",
  },
  font: {
    light: 300,
    normal: 400,
    bold: 600,
    sizes: {
      xsmall: "1.2rem",
      small: "1.4rem",
      medium: "1.6rem",
      large: "1.8rem",
      xlarge: "2.0rem",
      xxlarge: "2.8rem",
    },
  },
};
